apiVersion: v1
kind: PersistentVolumeClaim
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
# for this local-path storage to work in k3s you need to follow instructions at
# https://github.com/rancher/local-path-provisioner
# typically you need to apply at least once local-path-storage.yaml
# kubectl apply -f k3s-local-path-pvc.yml
# kubectl apply -f k3s-local-path-pvc.yml
metadata:
  name: go-cloud-k8s-shell-pvc
  namespace: go-testing
spec:
  accessModes:
    - ReadWriteOnce
# https://docs.k3s.io/storage
  storageClassName: local-path
  resources:
    requests:
      storage: 256Mi
