apiVersion: v1
kind: PersistentVolumeClaim
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
metadata:
  name: go-cloud-k8s-shell-pvc
  namespace: go-testing
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 256Mi
