apiVersion: v1
kind: PersistentVolumeClaim
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
metadata:
  name: longhorn-go-cloud-k8s-shell-pvc
  namespace: go-production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
