apiVersion: v1
kind: PersistentVolumeClaim
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
metadata:
  name: go-cloud-k8s-shell-pvc-read-write-once
  namespace: go-production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 512Mi
